version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
      
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - "5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      
  firefox:
    image: selenium/node-firefox-debug
    ports:
      - "5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      
  customer-module:
    image: yugz/selenium-demo:demo
    container_name: customer-module
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - MODULE=testNG_Sanity_lco.xml
      - BROWSER=firefox
      - HOST_HUB=selenium-hub
    volumes:
      - /home/user/customer-module-result:/output
  